name: Workflow with Custom Python Docker Image

on:
  push:
    branches:
      - main

jobs:
  pull_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v3

      - name: Pull Docker Image from Docker Hub
        run: |
          docker pull gautampatel14/custom-python-docker:v1.0

  make_api_call:
    needs: pull_docker_image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v3

      - name: Checkout Workflow Repository
        uses: actions/checkout@v3
        with:
          repository: gautampatel14/workflow
          path: workflow  # Setting the correct path

      - name: List files to verify structure
        run: |
          ls -R .  # Listing files to ensure correct structure and access

      - name: Run API Call with Error Handling
        run: |
          set -e
          docker run --rm -v $(pwd)/workflow:/app/workflow gautampatel14/custom-python-docker:v1.0 python /app/workflow/api_call.py
        continue-on-error: false

      - name: Upload API Response Artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: api_response
          path: workflow/response.json

  modify_response:
    needs: make_api_call
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v3

      - name: Checkout Workflow Repository
        uses: actions/checkout@v3
        with:
          repository: gautampatel14/workflow
          path: workflow

      - name: Download API Response Artifact
        uses: actions/download-artifact@v3
        with:
          name: api_response

      - name: Run Modify Response with Error Handling
        run: |
          set -e
          docker run --rm -v $(pwd)/workflow:/app/workflow gautampatel14/custom-python-docker:v1.0 python /app/workflow/modify_response.py
        continue-on-error: false

      - name: Upload Modified Response Artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: modified_response
          path: workflow/modified_response.json

      - name: Set Output Variable
        id: set-output
        if: success()
        run: |
          OUTPUT=$(cat workflow/modified_response.json)
          echo "::set-output name=modified_output::$OUTPUT"

  print_output:
    needs: modify_response
    runs-on: ubuntu-latest
    steps:
      - name: Print Modified Output
        run: |
          echo "${{ steps.set-output.outputs.modified_output }}"
