name: Workflow with Custom Python Docker Image

on: 
  push:
    branches:
      - main

jobs:
  pull_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v3  # Required to access the current repository
      
      - name: Pull Docker Image from Docker Hub
        run: |
          docker pull gautampatel14/custom-python-docker  # Pulling custom Docker image from Docker Hub

  make_api_call:
    needs: pull_docker_image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v3

      - name: Checkout Private Workflow Repository
        uses: actions/checkout@v3
        with:
          repository: gautampatel14/workflow  # Ensure correct repository access
          path: workflow

      - name: Run API Call with Error Handling
        run: |
          set -e  # Ensures script stops on errors
          docker run --rm -v $(pwd):/app gautampatel14/custom-python-docker python /app/workflow/init/api_call.py
        continue-on-error: false  # Ensures this step stops on error

      - name: Upload API Response Artifact
        if: success()  # Only execute if previous step succeeds
        uses: actions/upload-artifact@v3
        with:
          name: api_response
          path: response.json

  modify_response:
    needs: make_api_call
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v3

      - name: Checkout Private Workflow Repository
        uses: actions/checkout@v3
        with:
          repository: gautampatel14/workflow
          path: workflow

      - name: Download API Response Artifact
        uses: actions/download-artifact@v3
        with:
          name: api_response

      - name: Run Modify Response with Error Handling
        run: |
          set -e
          docker run --rm -v $(pwd):/app gautampatel14/custom-python-docker python /app/workflow/init/modify_response.py
        continue-on-error: false

      - name: Upload Modified Response Artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: modified_response
          path: modified_response.json

      - name: Set Output Variable
        id: set-output
        if: success()
        run: |
          OUTPUT=$(cat modified_response.json)
          echo "::set-output name=modified_output::$OUTPUT"

  print_output:
    needs: modify_response
    runs-on: ubuntu-latest
    steps:
      - name: Print Modified Output
        if: success()
        run: |
          echo "${{ needs.modify_response.outputs.modified_output }}"
